"""add_heatmap_relations

Revision ID: a44f4a23bcc3
Revises: c833b4eea99a
Create Date: 2025-05-11 22:41:49.878476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44f4a23bcc3'
down_revision: Union[str, None] = 'c833b4eea99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction_heatmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_length', sa.Integer(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('interaction_duration', sa.Float(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('emotion', sa.String(length=20), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('cognitive_load', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_heatmaps_timestamp'), 'interaction_heatmaps', ['timestamp'], unique=False)
    op.create_index(op.f('ix_interaction_heatmaps_user_id'), 'interaction_heatmaps', ['user_id'], unique=False)
    op.create_table('user_heatmap_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('peak_hours', sa.JSON(), nullable=True),
    sa.Column('weekly_pattern', sa.JSON(), nullable=True),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('engagement_trend', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('heatmap_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('subscription_tier', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('quantum_access', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('heatmap_preferences', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('voice_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('personality_matrix', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'personality_matrix')
    op.drop_column('users', 'voice_enabled')
    op.drop_column('users', 'heatmap_preferences')
    op.drop_column('users', 'quantum_access')
    op.drop_column('users', 'subscription_tier')
    op.drop_table('messages')
    op.drop_table('user_heatmap_profiles')
    op.drop_index(op.f('ix_interaction_heatmaps_user_id'), table_name='interaction_heatmaps')
    op.drop_index(op.f('ix_interaction_heatmaps_timestamp'), table_name='interaction_heatmaps')
    op.drop_table('interaction_heatmaps')
    op.drop_table('conversations')
    # ### end Alembic commands ###
